export const Avatar_Options = [
    "avatar1.jpg",
    "avatar2.jpg",
    "avatar3.jpg",
    "avatar4.jpg",
    "avatar5.jpg",
    "avatar6.jpg",
    "avatar7.jpg",
    "avatar8.jpg",
    "avatar9.jpg",
    "avatar10.jpg",
    "avatar11.jpg",
    "avatar12.jpg",
    "avatar13.jpg",
    "avatar14.jpg",
    "avatar15.jpg",
    "avatar16.jpg",
    "avatar17.jpg",
    "avatar18.jpg",
    "avatar19.jpg",
    "avatar20.jpg",
    "avatar21.jpg",
]

export const Avatar_Path = "/avatar/";