import Image from 'next/image'
import Link from 'next/link'
import React from 'react'
const examData = [
    {
        id: 1,
        image: "/exams/exam1.jpg",
        topic: "Mathematics",
        questions: 50,
        technology: "React, Node.js",
        generatedBy: "Admin",
    },
    {
        id: 2,
        image: "/exams/exam2.jpg",
        topic: "Physics",
        questions: 40,
        technology: "Next.js, Firebase",
        generatedBy: "Teacher",
    },
    {
        id: 3,
        image: "/exams/exam3.jpg",
        topic: "Chemistry",
        questions: 45,
        technology: "Vue, Express.js",
        generatedBy: "Admin",
    },
];
const page = () => {
  return (
    <main className="container mx-auto px-4 py-8">
            <h1 className="text-4xl font-bold text-center mb-10">All Exams</h1>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                {examData.map((exam) => (
                    <div key={exam.id} className="bg-white rounded shadow p-4">
                        <Image
                            src={exam.image}
                            alt={exam.topic}
                            width={500}
                            height={300}
                            className="w-full h-48 object-cover mb-4 rounded"
                        />
                        <h2 className="text-2xl font-semibold mb-2">{exam.topic}</h2>
                        <p className="mb-1">
                            <strong>Questions:</strong> {exam.questions}
                        </p>
                        <p className="mb-1">
                            <strong>Technology:</strong> {exam.technology}
                        </p>
                        <p className="mb-4">
                            <strong>MCQ Generated By:</strong> {exam.generatedBy}
                        </p>
                        <Link href={`/exams/${exam.id}`} className="text-blue-500 hover:underline">
                            View Details
                        </Link>
                    </div>
                ))}
            </div>
        </main>
  )
}

export default page